### ISSUE TITLE
Pdflatex error when setting title size

### ISSUE THREAD

**Issue by andeElliott** [alan-turing-institute/templates#6]
Uncommenting the line 

\setlength{\bodytext}{26pt}

results in the following error in pdflatex:

! Undefined control sequence.
<argument> \bodytext
l.16 \setlength{\bodytext}{26pt}

Dont know exactly how to fix this but will look into it.

**Comment by andeElliott** [comment]
See PR for this issue.

**Comment by martintoreilly** [comment]
Related PR is #7

**Comment by martintoreilly** [comment]
Closed by PR #7
